### PR TITLE
Make json_format a regular function.

### PR DESCRIPTION
**Pull request by batrick**

### CODE REVIEW

**Comment by batrick** [comment]
Seems to work with `chirp_status`:

```
$ ./chirp/src/chirp_status -c localhost -d all --verbose
2015/11/06 13:21:59.97 chirp_status[5063] debug: ./chirp/src/chirp_status version 6.0.0 [HEAD:eda5586b] (released 2015-11-06 12:33:14 -0500)
2015/11/06 13:21:59.97 chirp_status[5063] debug: Built by batrick@neverwinter.batbytes.com on 2015-11-06 13:16:57 -0500
2015/11/06 13:21:59.97 chirp_status[5063] debug: System: Linux neverwinter.batbytes.com 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
2015/11/06 13:21:59.97 chirp_status[5063] debug: Configuration: --debug --prefix /home/batrick/cctools/build
2015/11/06 13:21:59.97 chirp_status[5063] http: connect localhost port 9097
2015/11/06 13:21:59.97 chirp_status[5063] dns: looking up name localhost
2015/11/06 13:21:59.97 chirp_status[5063] dns: localhost is 127.0.0.1
2015/11/06 13:21:59.97 chirp_status[5063] tcp: connecting to 127.0.0.1:9097
2015/11/06 13:21:59.97 chirp_status[5063] tcp: made connection to 127.0.0.1:9097
2015/11/06 13:21:59.97 chirp_status[5063] http: GET http://localhost:9097/query.json HTTP/1.1
Connection: close
Host: localhost
User-Agent: Mozilla/5.0 (compatible; CCTools 6.0.0 [HEAD:eda5586b] Parrot; http://ccl.cse.nd.edu/)
2015/11/06 13:21:59.97 chirp_status[5063] http: HTTP/1.1 200 OK
2015/11/06 13:21:59.97 chirp_status[5063] http: Date: Fri Nov  6 13:21:59 2015
2015/11/06 13:21:59.97 chirp_status[5063] http: Server: catalog_server
2015/11/06 13:21:59.97 chirp_status[5063] http: Connection: close
2015/11/06 13:21:59.97 chirp_status[5063] http: Access-Control-Allow-Origin: *
2015/11/06 13:21:59.97 chirp_status[5063] http: Content-type: text/plain
2015/11/06 13:21:59.97 chirp_status[5063] http:
2015/11/06 13:21:59.97 chirp_status[5063] tcp: disconnected from 127.0.0.1:9097
[
{"url":0.000000,"total":87573676032,"cpus":4,"bytes_read":0,"lastheardfrom":1446834110,"address":"127.0.0.1","bytes_written":0,"project":0.000000,"load15":0.620000,"starttime":1446833900,"type":"chirp","memory_total":3860951040,"minfree":0,"opsysversion":"4.2.5-1-arch","cpu":0.000000,"owner":"batrick","name":"localhost.localdomain","clients":[],"memory_avail":810835968,"version":"6.0.0","opsys":"linux","total_ops":0,"port":10002,"backend":0.000000,"avail":39439028224,"load5":0.900000,"load1":0.390000},
{"url":0.000000,"total":87573676032,"cpus":4,"bytes_read":0,"lastheardfrom":1446834110,"address":"127.0.0.1","bytes_written":0,"project":0.000000,"load15":0.620000,"starttime":1446833900,"type":"chirp","memory_total":3860951040,"minfree":0,"opsysversion":"4.2.5-1-arch","cpu":0.000000,"owner":"batrick","name":"localhost.localdomain","clients":[],"memory_avail":813125632,"version":"6.0.0","opsys":"linux","total_ops":0,"port":10001,"backend":0.000000,"avail":39439028224,"load5":0.900000,"load1":0.390000},
{"url":0.000000,"total":87573676032,"cpus":4,"bytes_read":0,"lastheardfrom":1446834110,"address":"127.0.0.1","bytes_written":0,"project":0.000000,"load15":0.620000,"starttime":1446833900,"type":"chirp","memory_total":3860951040,"minfree":0,"opsysversion":"4.2.5-1-arch","cpu":0.000000,"owner":"batrick","name":"localhost.localdomain","clients":[],"memory_avail":809312256,"version":"6.0.0","opsys":"linux","total_ops":0,"port":10000,"backend":0.000000,"avail":39439028224,"load5":0.900000,"load1":0.390000},
{"url":0.000000,"total":87573676032,"cpus":4,"bytes_read":0,"lastheardfrom":1446834110,"address":"127.0.0.1","bytes_written":0,"project":0.000000,"load15":0.620000,"starttime":1446833900,"type":"chirp","memory_total":3860951040,"minfree":0,"opsysversion":"4.2.5-1-arch","cpu":0.000000,"owner":"batrick","name":"localhost.localdomain","clients":[],"memory_avail":802766848,"version":"6.0.0","opsys":"linux","total_ops":0,"port":10003,"backend":0.000000,"avail":39439028224,"load5":0.900000,"load1":0.390000},
{"url":0.000000,"total":87573676032,"cpus":4,"bytes_read":0,"lastheardfrom":1446834110,"address":"127.0.0.1","bytes_written":0,"project":0.000000,"load15":0.620000,"starttime":1446833900,"type":"chirp","memory_total":3860951040,"minfree":0,"opsysversion":"4.2.5-1-arch","cpu":0.000000,"owner":"batrick","name":"localhost.localdomain","clients":[],"memory_avail":802766848,"version":"6.0.0","opsys":"linux","total_ops":0,"port":10004,"backend":0.000000,"avail":39439028224,"load5":0.900000,"load1":0.390000}
]
```

**Comment by dthain** [comment]
Something is wrong here:`"url":0.000000`

**Comment by dthain** [comment]
Since it comes from `jx_format("chirp://%s:%s",...)`

**Comment by batrick** [comment]
That's interesting... I'll look into it.

**Comment by dthain** [comment]
This is the sort of problem I was running into when passing around a `va_list` as an argument.  it may have something to do with the object getting traversed more than once by `va_start` and `va_end`

**Comment by batrick** [comment]
So the string formatting is working properly. The issue is that the catalog's conversion of the nvpairs to json is wrong. Starting here:

https://github.com/dthain/cctools/blob/eda5586b618c4cf4d8d930b212364cb2b8ff2fdb/dttools/src/catalog_server.c#L384

calls

https://github.com/dthain/cctools/blob/eda5586b618c4cf4d8d930b212364cb2b8ff2fdb/dttools/src/nvpair_jx.c#L81

calls

https://github.com/dthain/cctools/blob/eda5586b618c4cf4d8d930b212364cb2b8ff2fdb/dttools/src/stringtools.c#L672

problem is here:

https://github.com/dthain/cctools/blob/eda5586b618c4cf4d8d930b212364cb2b8ff2fdb/dttools/src/stringtools.c#L683-L684

There's no break if the string has no number digits.

I would suggest removing the string_tool's is_float/is_integer and using strtod/strtol instead. These functions will fail if the string is not a number. You can check the endptr for failure, from strtod(3):

```
       If no conversion is performed, zero is returned  and  the  value  of  nptr  is
       stored in the location referenced by endptr.
```

**Comment by batrick** [comment]
To add onto this

> There's no break if the string has no number digits.

The is_float function is traversing the entire url string `chirp://foo:1024/` and finds number digits `1024`. So the function returns that it is a float. When we run `atod`, the function fails with 0.0 returned.

**Comment by dthain** [comment]
Aha, my dumb mistake, thanks for catching it.
I made a 30 second fix, but strtol is a much better idea for later.
Please rebase and see if your pull still works.

**Comment by batrick** [comment]
Done.

**Comment by batrick** [comment]
Testing...

**Comment by batrick** [comment]
`chirp_status` is working for me now.

**Pull request merged**
